apiVersion: v1
kind: Service
metadata:
  name: openwebui-oauth-proxy
  namespace: {{ .Values.namespace }}
  labels:
    app: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "41"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.oauthProxyPort }}
      targetPort: oauth-proxy
      protocol: TCP
      name: oauth-proxy
  selector:
    app: openwebui
