apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openwebui-anyuid-scc-binding
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: openwebui
    namespace: {{ .Values.namespace }}
