apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openwebui
  namespace: {{ .Values.namespace }}
  labels:
    app: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "42"
spec:
  to:
    kind: Service
    name: openwebui-oauth-proxy
  port:
    targetPort: oauth-proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
