apiVersion: v1
kind: ServiceAccount
metadata:
  name: openwebui
  namespace: {{ .Values.namespace }}
  labels:
    app: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    serviceaccounts.openshift.io/oauth-redirectreference.openwebui: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"openwebui"}}'
